Repository jenkinsci/mcp-server-plugin, pull requests merged in 2025-09, with the labels that each got.

#45 Update README to include getStatus tool
  README.md
Labels: documentation

#50 Added some more documentation
  README.md
Labels: documentation

#49 add explicit annotation for the nondestructive tools
  src/main/java/io/jenkins/plugins/mcp/server/extensions/BuildLogsExtension.java
  src/main/java/io/jenkins/plugins/mcp/server/extensions/DefaultMcpServer.java
  src/main/java/io/jenkins/plugins/mcp/server/extensions/JobScmExtension.java
Labels: enhancement

#59 disable test on windows
  src/test/java/io/jenkins/plugins/mcp/server/extensions/DefaultMcpServerTest.java
Labels: skip-changelog

#61 Upgrade mcp sdk to 0.13.1
  README.md
  pom.xml
  src/main/java/io/jenkins/plugins/mcp/server/Endpoint.java
  src/main/java/io/jenkins/plugins/mcp/server/servlet/UserContextHttpRequest.java
  src/main/java/io/jenkins/plugins/mcp/server/tool/McpToolWrapper.java
Labels: documentation, dependencies
